name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.803
    - name: Build with dotnet
      run: dotnet build src/ParameterStore.Lambda/ParameterStoreDemo.Lambda.csproj --configuration Release
    - name: Run Unit Tests
      run: dotnet test test/ParameterStoreDemo.Tests/ParameterStoreDemo.Tests.csproj
    - name: Run Unit Tests
      run: dotnet build src/ParameterStore.Lambda/ParameterStoreDemo.Lambda.csproj --configuration Release
    - name: cdk deploy
      uses: two4suited/aws-cdk-dotnet-github-action@master
      with:
        cdk_subcommand: 'deploy'
        actions_comment: false
        args: '--require-approval never'
        working_dir: 'src/ParameterStore.Infrastructure'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-west-2'

